# In _config.yml
title: Computing Lab
author: Adrian Barnes and Francesco Turci
#logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
